### ISSUE TITLE
Update TTNv3 Project

### ISSUE THREAD

**Issue by mpfeil** [sensebox/sensebox-reboot#154]
Das TTNv3 Projekt müsste an folgenden Stellen angepasst werden:

1. LoRaWAN version & Regional Parameters version unter Register end device haben sich geändert. Sind jetzt: `LoRaWAN Specification 1.0.2 & RP001 Regional Parameters 1.0.2 revision 2`
3. `{}` Klammern müssen bei den EUIs nicht mehr kopiert werden (`Blockly` Abschnitt)

Link zum Projekt: https://github.com/sensebox/sensebox-reboot/blob/master/_projects/de/2021-02-19-TTNv3.md

**Comment by PaulReichmuth** [comment]
Müssen alte Devices auf die neuen Spezifikationen angepasst werden? Dann würde ich noch einen entsprechenden Hinweis einfügen.

**Comment by mpfeil** [comment]
Das weiß ich leider nicht. Bin mir auch nicht sicher, was ich bei meiner alten TTN Station eingestellt hatte und ob die alten Werte automatisch auf die neuen umgestellt wurden.

**Comment by PaulReichmuth** [comment]
Habe grade mal nachgeschaut, die alten Werte sind automatisch geändert worden, scheint aber so als wäre ein neuer join nötig. Werde dann einen entsprechenden Hinweis hinsetzen.
